version: '2.3'
services:
  NOTIFO_mongo:
    image: mongo:5
    volumes:
      - /etc/notifo/mongo/db:/data/db
    networks:
      - internal
    restart: unless-stopped

  NOTIFO_notifo:
    image: "squidex/notifo:1"
    ports:
      - "80:5000"
    environment:
      - URLS__BASEURL=https://${NOTIFO_DOMAIN}
      - STORAGE__MONGODB__CONNECTIONSTRING=mongodb://notifo_mongo
      - IDENTITY__GOOGLECLIENT=${NOTIFO_GOOGLECLIENT}
      - IDENTITY__GOOGLESECRET=${NOTIFO_GOOGLESECRET}
      - IDENTITY__GITHUBCLIENT=${NOTIFO_GITHUBCLIENT}
      - IDENTITY__GITHUBSECRET=${NOTIFO_GITHUBSECRET}
      - IDENTITY__MICROSOFTCLIENT=${NOTIFO_MICROSOFTCLIENT}
      - IDENTITY__MICROSOFTSECRET=${NOTIFO_MICROSOFTSECRET}
      - ASPNETCORE_URLS=http://+:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
      start_period: 60s
    depends_on:
      - NOTIFO_mongo
    volumes:
      - /etc/notifo/assets:/app/Assets
    networks:
      - internal
    restart: unless-stopped
    
networks:
  internal:
    driver: bridge