version: '2.3'
services:
  squidex_mongo:
    image: mongo:4.4.1
    volumes:
      - /etc/notifo/mongo/db:/data/db
    networks:
      - internal
    restart: unless-stopped

  notifo_notifo:
    image: "notifo/notifo:1"
    environment:
      - URLS__BASEURL=https://<YOUR_DOMAIN>/
      - MONGODB__CONNECTIONSTRING=mongodb://notifo_mongo
      - IDENTITY__USERS__0__EMAIL=<YOUR_ADMIN_EMAIL>
      - IDENTITY__USERS__0__PASSWORD=<YOUR_ADMIN_PASSWORD>
      - IDENTITY__GOOGLECLIENT=
      - IDENTITY__GOOGLESECRET=
      - IDENTITY__GITHUBCLIENT=
      - IDENTITY__GITHUBSECRET=
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - notifo_mongo
    networks:
      - internal
    restart: unless-stopped

  squidex_proxy:
    image: squidex/caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SITE_ADDRESS=<YOUR_DOMAIN>
      - SITE_SERVER="notifo_notifo:5000"
    volumes:
      - /etc/notifo/caddy/data:/data
      - /etc/notifo/caddy/config:/config
    depends_on:
      - notifo_notifo
    networks:
      - internal
    restart: unless-stopped
    
networks:
  internal:
    driver: bridge