name: Build and Push to Dockerhub

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Calculate Version
      env:
        BUILD_NUMBER: ${{ github.run_number }}
      run: |
        echo "BUILD_NUMBER=$(($BUILD_NUMBER + 210))" >> $GITHUB_ENV
  
    - name: Set up qemu
      uses: docker/setup-qemu-action@v1
    
    - name: Set up buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: BUILD AND PUSH
      id: docker_build
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.ref == 'refs/heads/main' }}
        cache-from: type=registry,ref=squidex/notifo:cache-dev
        cache-to: type=registry,ref=squidex/notifo:cache-dev
        tags: squidex/notifo:dev-${{ env.BUILD_NUMBER }}

    - name: BUILD AND PUSH PR
      id: docker_build_pr
      if: github.event_name == 'pull_request'
      uses: docker/build-push-action@v2
      with:
        push: false
