name: Build and Push to Dockerhub
concurrency: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get Major Version
      id: version
      uses: rishabhgupta/split-by@v1
      with:
        string: '${{ env.GITHUB_REF_SLUG }}'
        split-by: '.'

    - name: Print Major Version
      run: | 
        echo "Major Version: ${{ steps.version.outputs._0 }} for ${{ env.GITHUB_REF_SLUG }}"

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - name: Login to Docker
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: BUILD
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        load: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        tags: notifo-temp

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Rename Tags
      if: github.event_name != 'pull_request'
      run: |
        docker tag notifo-temp squidex/notifo:dev-latest
        docker tag notifo-temp squidex/notifo:${{ env.GITHUB_REF_SLUG }}
        docker tag notifo-temp squidex/notifo:${{ steps.version.outputs._0 }}

    - name: Push Tags
      if: github.event_name != 'pull_request'
      run: |
        docker push squidex/notifo:dev-latest
        docker push squidex/notifo:${{ env.GITHUB_REF_SLUG }}
        docker push squidex/notifo:${{ steps.version.outputs._0 }}


