name: Build and Push to Dockerhub

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: calculate version
      env:
        BUILD_NUMBER: ${{ github.run_number }}
      run: |
        echo "BUILD_NUMBER=$(($BUILD_NUMBER + 210))" >> $GITHUB_ENV
  
    - name: setup qemu
      uses: docker/setup-qemu-action@v1
    
    - name: setup buildx
      uses: docker/setup-buildx-action@v1
    
    - name: login to docker
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build and push
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        cache-from: type=registry,ref=squidex/notifo:cache-dev
        cache-to: type=registry,ref=squidex/notifo:cache-dev
        tags: squidex/notifo:dev-${{ env.BUILD_NUMBER }}
